[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "groq>=0.26.0",
    "mistralai>=1.8.1",
    "pillow>=11.2.1",
    "streamlit>=1.45.1",
]
